export const GET_SUMMARY_STARTED = 'GET_SUMMARY_STARTED';
export const GET_SUMMARY_SUCCESS = 'GET_SUMMARY_SUCCESS';
export const GET_SUMMARY_FAILED = 'GET_SUMMARY_FAILED';
export const UPDATE_SUMMARY_LIST = 'UPDATE_SUMMARY_LIST';

export const GET_COUNTRIES_STARTED = 'GET_COUNTRIES_STARTED';
export const GET_COUNTRIES_SUCCESS = 'GET_COUNTRIES_SUCCESS';
export const GET_COUNTRIES_FAILED = 'GET_COUNTRIES_FAILED';

export const GET_HISTORY_BY_COUNTRY_STARTED = 'GET_HISTORY_BY_COUNTRY_STARTED';
export const GET_HISTORY_BY_COUNTRY_SUCCESS = 'GET_HISTORY_BY_COUNTRY_SUCCESS';
export const GET_HISTORY_BY_COUNTRY_FAILED = 'GET_HISTORY_BY_COUNTRY_FAILED';

export const GET_COUNTRY_OPTIONS_STARTED = 'GET_COUNTRY_OPTIONS_STARTED';
export const GET_COUNTRY_OPTIONS_SUCCESS = 'GET_COUNTRY_OPTIONS_SUCCESS';
export const GET_COUNTRY_OPTIONS_FAILED  = 'GET_COUNTRY_OPTIONS_FAILED';
